### ISSUE TITLE
请问使用rc.txt 文件 连接到QGC 但是 Summary 不显示。 怎么解决？

### ISSUE THREAD

**Issue by MyHu-2030** [LiuWhale/PX4-with-Simulink-Tutorial#1]
在simulink把ACM0端口的mavlink打开后
![enable_mavlink](https://user-images.githubusercontent.com/82227526/167368812-d0510d2a-297a-40bb-9c9d-2356b0f4ac15.png)
能够在QGC的”MAVLInk Inspector" 里面看到数据 
![m_I](https://user-images.githubusercontent.com/82227526/167369132-6b0fa353-496d-4ebd-a4ee-eb487e858036.png)
但是QGC的“Summary"  **不显示**  请问怎么解决？
![summary](https://user-images.githubusercontent.com/82227526/167369485-c968781f-5fcd-45b0-9126-369ae4920826.png)

**Comment by LiuWhale** [comment]
首先，这个问题主要是由于自定义的启动脚本(SD卡中的rc.txt)里没有启用Commander和Navigator的缘故。详情可以看如下两个链接：

- [Custom Startup Script in UAV Toolbox Support Package for PX4 Autopilots](https://www.mathworks.com/help/releases/R2022a/supportpkg/px4/ug/custom-startup-script.html)
- [Impact of Disabling MAVLink, Commander, and Navigator Modules](https://www.mathworks.com/help/releases/R2022a/supportpkg/px4/ug/impact-disabling-px4.html)
说到解决办法我想可以试一试在插件设置中选择rcs，默认使用启动脚本试一试
<img width="506" alt="image" src="https://user-images.githubusercontent.com/20088521/167456525-973b5e08-5fb8-4cf6-812f-5af802dd87b5.png">
或者在自定义启动脚本中启动Commander和Navigator试一试。

 期待你的测试恢复。

**Comment by MyHu-2030** [comment]
十分感谢您的回答
按照您指出的在自定义启动脚本中启动Commander和Navigator
![commander_navigator](https://user-images.githubusercontent.com/82227526/167522632-beedefea-b26b-448b-9118-444f10e4c4cb.png)
**_### 问题得到了解决_**
![rc_sol](https://user-images.githubusercontent.com/82227526/167522943-17b61eb9-8de4-4075-88f6-9dc093f6daf2.png)

**Comment by LiuWhale** [comment]
可以熬~
