### ISSUE TITLE
I've a problem when i deploy my simulink model on the hardware ( PX4) my drone spin on itself ( NO PID ) it means normally the drone goes only UP 

### ISSUE THREAD

**Issue by joyquad** [LiuWhale/PX4-with-Simulink-Tutorial#2]

**Comment by LiuWhale** [comment]
If you do not have any control algorithm, and only output the same pwms' value to the servos, the drone can only go up indeed. 
ps: If i understand your problem wrong, please be supplement.

**Comment by LiuWhale** [comment]
Closed.
